DROP TABLE IF EXISTS shopping_list;
DROP TYPE IF EXISTS grocery;

CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    category grocery NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL
);
