
INSERT INTO shopping_list (name, price, category, checked, date_added)
VALUES
    ('Fish tricks', 1310, 'Main',              false,  now() - '21 days'::INTERVAL),
    ('Not Dogs', 499, 'Snack',                 true,   now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 550, 'Snack',           false,  now() - '21 days'::INTERVAL),
    ('SubstiTuna Salad', 124, 'Lunch',         false,  now() - '21 days'::INTERVAL),
    ('Tofurkey', 250, 'Breakfast',             false,  now() - '21 days'::INTERVAL),
    ('Pretenderloins', 999, 'Main',            false,  now() - '9 days'::INTERVAL),
    ('Steak-believe', 600, 'Main',             false,  now() - '9 days'::INTERVAL),
    ('Kale Seitan', 667, 'Breakfast',          false,  now() - '9 days'::INTERVAL),
    ('NoBull Burger', 200, 'Snack',            false,  now() - '9 days'::INTERVAL),
    ('Turnip the Beet', 020, 'Lunch',          true,   now() - '9 days'::INTERVAL),
    ('Mascarphony', 180, 'Lunch',              true,   now() - '7 days'::INTERVAL),
    ('Burgatory', 150, 'Main',                 false,  now() - '7 days'::INTERVAL),
    ('Sleight of Ham', 310, 'Lunch',           false,  now() - '5 days'::INTERVAL),
    ('Antichovies', 100, 'Breakfast',          false,  now() - '5 days'::INTERVAL),
    ('Lettuce B. Frank', 086, 'Lunch',         true,   now() - '5 days'::INTERVAL),
    ('Pepperphony', 140, 'Breakfast',          false,  now() - '5 days'::INTERVAL),
    ('Shamburger', 350, 'Main',                false,  now() - '4 days'::INTERVAL),
    ('Facon', 190, 'Breakfast',                false,  now() - '4 days'::INTERVAL),
    ('Salami-get-this-straight', 300, 'Snack', false,  now() - '4 days'::INTERVAL),
    ('Mi-steak', 767, 'Main',                  false,  now() - '3 days'::INTERVAL),
    ('Ghost Beef', 433, 'Main',                false,  now() - '3 days'::INTERVAL),
    ('Cheatloaf', 500, 'Main',                 false,  now() - '3 days'::INTERVAL),
    ('Fried Trickin', 640, 'Snack',            false,  now() - '3 days'::INTERVAL),
    ('Salmock', 716, 'Breakfast',              false,  now() - '3 days'::INTERVAL),
    ('Leaf Stroganoff', 680, 'Main',           false,  now() - '2 days'::INTERVAL),
    ('Chicken Noodle Spoof', 250, 'Lunch',     false,  now() - '2 days'::INTERVAL),
    ('Pep-parody Pizza', 400, 'Lunch',         false,  now() - '2 days'::INTERVAL),
    ('Arti-fish-al pie', 840, 'Main',          false,  now() - '1 days'::INTERVAL),
    ('Bolphony sandwiches', 210, 'Lunch',      false,  now()),
    ('Chili non-carne', 588, 'Main',           true,   now()),
    ('Don''t go bacon my heart', 420, 'Main',  false,  now())
;
